// [BILL-DBG preview hook] ObjectnextBillPreview: undefinedtenantId: "b0c8e6d5-4528-468f-94e6-e0fd97dde8b1"[[Prototype]]: Object
// wgbhffmgqilsxlrsowqb.supabase.co/rest/v1/bills?select=bill_number&tenant_id=eq.b0c8e6d5-4528-468f-94e6-e0fd97dde8b1&bill_number=ilike.INV-2026%2F09%2F29-%25&order=created_at.desc&limit=1:1  Failed to load resource: the server responded with a status of 406 ()
// 0_dtx.~oahr~b.js:49 [BILL-DBG preview fn] ObjectlastBill: nullnextSeq: 1prefix: "INV-2026/09/29-"result: "INV-2026/09/29-1"[[Prototype]]: Object
// 05.e_u_m_xija.js:71 [BILL-DBG preview hook] ObjectnextBillPreview: "INV-2026/09/29-1"tenantId: "b0c8e6d5-4528-468f-94e6-e0fd97dde8b1"[[Prototype]]: Object
// 05.e_u_m_xija.js:71 [BILL-DBG preview hook] ObjectnextBillPreview: "INV-2026/09/29-1"tenantId: "b0c8e6d5-4528-468f-94e6-e0fd97dde8b1"[[Prototype]]: Object
// 0j9kyohpeo1im.js:1 [DEBUG - BillForm] Setting bill_number to preview: INV-2026/09/29-1
// 0j9kyohpeo1im.js:1 [DEBUG - BillForm] RAW form data generated by React Hook Form: Object
// 0j9kyohpeo1im.js:1 [DEBUG - BillForm] FINAL data being sent to parent onSubmit: Objectbill_date: "2026-08-21"bill_number: "INV-2026/08/21-B1234"[[Prototype]]: Object
// 05.e_u_m_xija.js:71 [DEBUG - page.tsx] Payload received from BillForm: Object
// 0_dtx.~oahr~b.js:49 
// === [DEBUG - createBill] ===
// 0_dtx.~oahr~b.js:50 [DEBUG - API] 1. Incoming Bill Data: {
//   "bill_number": "INV-2026/08/21-B1234",
//   "customer_type": "flying",
//   "customer_name": "Testing",
//   "customer_phone": "7894561552",
//   "customer_id": "88fc885c-6af5-4ea5-bdb9-63ee31b6650a",
//   "bill_date": "2026-08-21",
//   "due_date": "",
//   "vehicle_no": "7415",
//   "reference_name": "",
//   "terms_conditions": "",
//   "status": "issued",
//   "is_gst_bill": false,
//   "is_interstate": false,
//   "subtotal": 2960,
//   "round_off": 0,
//   "discount_amount": 0,
//   "cgst_total": 0,
//   "sgst_total": 0,
//   "igst_total": 0,
//   "grand_total": 2960,
//   "total_profit": 434,
//   "amount_paid": 0,
//   "amount_due": 2960,
//   "payment_method": "credit",
//   "notes": "",
//   "bill_line_items": [
//     {
//       "item_name": "Bearing",
//       "hsn_code": "84828000",
//       "unit": "Pcs",
//       "qty": 1,
//       "unit_price": 1160,
//       "discount_pct": 0,
//       "gst_rate": 0,
//       "cgst": 0,
//       "sgst": 0,
//       "igst": 0,
//       "line_total": 1160,
//       "sort_order": 0,
//       "total_buy_price": 982,
//       "line_profit": 178,
//       "batch_allocations": [
//         {
//           "batch_id": "ed56a060-6370-4398-a2d0-697cad866cda",
//           "qty": 1,
//           "buy_price": 982,
//           "batch_number": "OPENING-STOCK"
//         }
//       ],
//       "write_off_recovery": 0,
//       "item_id": "639e6b8f-d72a-40cb-bd43-cfa6651127a4"
//     },
//     {
//       "item_name": "Fuel FilterBS2/3",
//       "hsn_code": "84212300",
//       "unit": "Pcs",
//       "qty": 1,
//       "unit_price": 1800,
//       "discount_pct": 0,
//       "gst_rate": 0,
//       "cgst": 0,
//       "sgst": 0,
//       "igst": 0,
//       "line_total": 1800,
//       "sort_order": 1,
//       "total_buy_price": 1544,
//       "line_profit": 256,
//       "batch_allocations": [
//         {
//           "batch_id": "980d6592-8d31-482a-9b65-b17660247dc2",
//           "qty": 1,
//           "buy_price": 1544,
//           "batch_number": "OPENING-STOCK"
//         }
//       ],
//       "write_off_recovery": 0,
//       "item_id": "1722da37-9a82-4737-85c6-25134294aca7"
//     }
//   ]
// }
// 05.e_u_m_xija.js:71 [BILL-DBG preview hook] Object
// 0_dtx.~oahr~b.js:50 [DEBUG - API] 2. Safe Bill Data: {
//   "bill_number": "INV-2026/08/21-B1234",
//   "customer_type": "flying",
//   "customer_name": "Testing",
//   "customer_phone": "7894561552",
//   "customer_id": "88fc885c-6af5-4ea5-bdb9-63ee31b6650a",
//   "bill_date": "2026-08-21",
//   "due_date": "",
//   "vehicle_no": "7415",
//   "reference_name": "",
//   "terms_conditions": "",
//   "status": "issued",
//   "is_gst_bill": false,
//   "is_interstate": false,
//   "subtotal": 2960,
//   "round_off": 0,
//   "discount_amount": 0,
//   "cgst_total": 0,
//   "sgst_total": 0,
//   "igst_total": 0,
//   "grand_total": 2960,
//   "total_profit": 434,
//   "amount_paid": 0,
//   "amount_due": 2960,
//   "payment_method": "credit",
//   "notes": "",
//   "bill_line_items": [
//     {
//       "item_name": "Bearing",
//       "hsn_code": "84828000",
//       "unit": "Pcs",
//       "qty": 1,
//       "unit_price": 1160,
//       "discount_pct": 0,
//       "gst_rate": 0,
//       "cgst": 0,
//       "sgst": 0,
//       "igst": 0,
//       "line_total": 1160,
//       "sort_order": 0,
//       "total_buy_price": 982,
//       "line_profit": 178,
//       "batch_allocations": [
//         {
//           "batch_id": "ed56a060-6370-4398-a2d0-697cad866cda",
//           "qty": 1,
//           "buy_price": 982,
//           "batch_number": "OPENING-STOCK"
//         }
//       ],
//       "write_off_recovery": 0,
//       "item_id": "639e6b8f-d72a-40cb-bd43-cfa6651127a4"
//     },
//     {
//       "item_name": "Fuel FilterBS2/3",
//       "hsn_code": "84212300",
//       "unit": "Pcs",
//       "qty": 1,
//       "unit_price": 1800,
//       "discount_pct": 0,
//       "gst_rate": 0,
//       "cgst": 0,
//       "sgst": 0,
//       "igst": 0,
//       "line_total": 1800,
//       "sort_order": 1,
//       "total_buy_price": 1544,
//       "line_profit": 256,
//       "batch_allocations": [
//         {
//           "batch_id": "980d6592-8d31-482a-9b65-b17660247dc2",
//           "qty": 1,
//           "buy_price": 1544,
//           "batch_number": "OPENING-STOCK"
//         }
//       ],
//       "write_off_recovery": 0,
//       "item_id": "1722da37-9a82-4737-85c6-25134294aca7"
//     }
//   ]
// }
// 0_dtx.~oahr~b.js:50 [DEBUG - API] 3. Final DB Insert Payload -> finalBillNumber: "INV-2026/08/21-B1234", finalBillDate: "2026-08-21" {
//   "bill_number": "INV-2026/08/21-B1234",
//   "customer_type": "flying",
//   "customer_name": "Testing",
//   "customer_phone": "7894561552",
//   "customer_id": "88fc885c-6af5-4ea5-bdb9-63ee31b6650a",
//   "bill_date": "2026-08-21",
//   "due_date": "",
//   "vehicle_no": "7415",
//   "reference_name": "",
//   "terms_conditions": "",
//   "status": "issued",
//   "is_gst_bill": false,
//   "is_interstate": false,
//   "subtotal": 2960,
//   "round_off": 0,
//   "discount_amount": 0,
//   "cgst_total": 0,
//   "sgst_total": 0,
//   "igst_total": 0,
//   "grand_total": 2960,
//   "total_profit": 434,
//   "amount_paid": 0,
//   "amount_due": 2960,
//   "payment_method": "credit",
//   "notes": "",
//   "bill_line_items": [
//     {
//       "item_name": "Bearing",
//       "hsn_code": "84828000",
//       "unit": "Pcs",
//       "qty": 1,
//       "unit_price": 1160,
//       "discount_pct": 0,
//       "gst_rate": 0,
//       "cgst": 0,
//       "sgst": 0,
//       "igst": 0,
//       "line_total": 1160,
//       "sort_order": 0,
//       "total_buy_price": 982,
//       "line_profit": 178,
//       "batch_allocations": [
//         {
//           "batch_id": "ed56a060-6370-4398-a2d0-697cad866cda",
//           "qty": 1,
//           "buy_price": 982,
//           "batch_number": "OPENING-STOCK"
//         }
//       ],
//       "write_off_recovery": 0,
//       "item_id": "639e6b8f-d72a-40cb-bd43-cfa6651127a4"
//     },
//     {
//       "item_name": "Fuel FilterBS2/3",
//       "hsn_code": "84212300",
//       "unit": "Pcs",
//       "qty": 1,
//       "unit_price": 1800,
//       "discount_pct": 0,
//       "gst_rate": 0,
//       "cgst": 0,
//       "sgst": 0,
//       "igst": 0,
//       "line_total": 1800,
//       "sort_order": 1,
//       "total_buy_price": 1544,
//       "line_profit": 256,
//       "batch_allocations": [
//         {
//           "batch_id": "980d6592-8d31-482a-9b65-b17660247dc2",
//           "qty": 1,
//           "buy_price": 1544,
//           "batch_number": "OPENING-STOCK"
//         }
//       ],
//       "write_off_recovery": 0,
//       "item_id": "1722da37-9a82-4737-85c6-25134294aca7"
//     }
//   ]
// }
// 0_dtx.~oahr~b.js:43 [DEBUG - INVENTORY] Create Bill applied -1 to batch ed56a060-6370-4398-a2d0-697cad866cda.
// 0_dtx.~oahr~b.js:43 [DEBUG - INVENTORY] Create Bill applied -1 to batch 980d6592-8d31-482a-9b65-b17660247dc2.
// 0_dtx.~oahr~b.js:50 [DEBUG] Bill successfully created with ID: 929c3ea7-9709-44ce-9879-36378dfcd163
// 0_dtx.~oahr~b.js:50 === [DEBUG - createBill END] ===

// 05.e_u_m_xija.js:71 [BILL-DBG preview hook] Object
// 0_dtx.~oahr~b.js:28 [DEBUG - API] Fetching Bill ID: 929c3ea7-9709-44ce-9879-36378dfcd163 for Tenant: b0c8e6d5-4528-468f-94e6-e0fd97dde8b1
// 0_dtx.~oahr~b.js:43 [DEBUG - API] fetchBillById Supabase Result: Objectdata: {id: '929c3ea7-9709-44ce-9879-36378dfcd163', tenant_id: 'b0c8e6d5-4528-468f-94e6-e0fd97dde8b1', customer_id: 'e6a4ad9d-3edc-4031-bbb8-8c2e4457aa79', created_by: '27a717fa-1f12-47df-9ab6-b6963cd42ddc', bill_number: 'INV-2026/08/21-B1234', …}error: null[[Prototype]]: Object
// 0j9kyohpeo1im.js:1 [DEBUG - BillForm] Setting bill_number to preview: undefined
// 0j9kyohpeo1im.js:1 [DEBUG - BillForm] RAW form data generated by React Hook Form: Objectbill_date: "2026-08-21"bill_number: "INV-2026/08/21-B1234"[[Prototype]]: Object
// 0j9kyohpeo1im.js:1 [DEBUG - BillForm] FINAL data being sent to parent onSubmit: Objectbill_date: "2026-08-21"bill_number: "INV-2026/08/21-B1234"[[Prototype]]: Object
// 0_dtx.~oahr~b.js:51 
// === [DEBUG - updateBill] ===
// 0_dtx.~oahr~b.js:52 [DEBUG - API] 1. Initial Data received by API -> bill_number: "INV-2026/08/21-B1234", bill_date: "2026-08-21"
// 0_dtx.~oahr~b.js:52 [DEBUG - updateBill] Held Batches Map calculated: Object
// 0_dtx.~oahr~b.js:52 [DEBUG - updateBill] Active Batches Map sent to Engine: {
//   "639e6b8f-d72a-40cb-bd43-cfa6651127a4": [
//     {
//       "id": "ed56a060-6370-4398-a2d0-697cad866cda",
//       "po_id": null,
//       "item_id": "639e6b8f-d72a-40cb-bd43-cfa6651127a4",
//       "buy_price": 982,
//       "stock_qty": 2,
//       "tenant_id": "b0c8e6d5-4528-468f-94e6-e0fd97dde8b1",
//       "created_at": "2026-08-30T12:45:59.239571+00:00",
//       "sell_price": 1160,
//       "batch_number": "OPENING-STOCK"
//     }
//   ],
//   "1722da37-9a82-4737-85c6-25134294aca7": [
//     {
//       "id": "980d6592-8d31-482a-9b65-b17660247dc2",
//       "po_id": null,
//       "item_id": "1722da37-9a82-4737-85c6-25134294aca7",
//       "buy_price": 1544,
//       "stock_qty": 4,
//       "tenant_id": "b0c8e6d5-4528-468f-94e6-e0fd97dde8b1",
//       "created_at": "2026-08-30T13:02:00.86778+00:00",
//       "sell_price": 1800,
//       "batch_number": "OPENING-STOCK"
//     }
//   ]
// }
// 0_dtx.~oahr~b.js:52 [DEBUG - API] 2. Data AFTER CalculationEngine -> bill_number: "INV-2026/08/21-B1234", bill_date: "2026-08-21"
// 0_dtx.~oahr~b.js:52 [DEBUG - API] 3. Final DB Update Payload -> finalBillNumber: "INV-2026/08/21-B1234", finalBillDate: "2026-08-21"
// 0_dtx.~oahr~b.js:43 [DEBUG - INVENTORY] Update Bill (Revert) applied 1 to batch ed56a060-6370-4398-a2d0-697cad866cda.
// 0_dtx.~oahr~b.js:43 [DEBUG - INVENTORY] Update Bill (Revert) applied 1 to batch 980d6592-8d31-482a-9b65-b17660247dc2.
// 0_dtx.~oahr~b.js:43 [DEBUG - INVENTORY] Update Bill (Apply) applied -1 to batch ed56a060-6370-4398-a2d0-697cad866cda.
// 0_dtx.~oahr~b.js:43 [DEBUG - INVENTORY] Update Bill (Apply) applied -1 to batch 980d6592-8d31-482a-9b65-b17660247dc2.
// 0_dtx.~oahr~b.js:52 [DEBUG] Bill successfully updated.
// 0_dtx.~oahr~b.js:52 === [DEBUG - updateBill END] ===

// 0_dtx.~oahr~b.js:28 [DEBUG - API] Fetching Bill ID: 929c3ea7-9709-44ce-9879-36378dfcd163 for Tenant: b0c8e6d5-4528-468f-94e6-e0fd97dde8b1
// 0_dtx.~oahr~b.js:43 [DEBUG - API] fetchBillById Supabase Result: Object
// 05.e_u_m_xija.js:71 [BILL-DBG preview hook] Object
// wgbhffmgqilsxlrsowqb.supabase.co/rest/v1/bills?select=bill_number&tenant_id=eq.b0c8e6d5-4528-468f-94e6-e0fd97dde8b1&bill_number=ilike.INV-2026%2F09%2F29-%25&order=created_at.desc&limit=1:1  Failed to load resource: the server responded with a status of 406 ()
// 0_dtx.~oahr~b.js:49 [BILL-DBG preview fn] Object
// 05.e_u_m_xija.js:71 [BILL-DBG preview hook] Object
// 0j9kyohpeo1im.js:1 [DEBUG - BillForm] Setting bill_number to preview: INV-2026/09/29-1
// 0j9kyohpeo1im.js:1 [DEBUG - BillForm] RAW form data generated by React Hook Form: Object
// 0j9kyohpeo1im.js:1 [DEBUG - BillForm] FINAL data being sent to parent onSubmit: Object
// 05.e_u_m_xija.js:71 [DEBUG - page.tsx] Payload received from BillForm: Object
// 0_dtx.~oahr~b.js:49 
// === [DEBUG - createBill] ===
// 0_dtx.~oahr~b.js:50 [DEBUG - API] 1. Incoming Bill Data: {
//   "bill_number": "INV-2026/07/14-B2345",
//   "customer_type": "flying",
//   "customer_name": "Testing bill",
//   "customer_phone": "7894561541",
//   "customer_id": "5341150c-7aa5-49d3-9a77-05a15cace3f1",
//   "bill_date": "2026-07-14",
//   "due_date": "",
//   "vehicle_no": "",
//   "reference_name": "",
//   "terms_conditions": "",
//   "status": "issued",
//   "is_gst_bill": false,
//   "is_interstate": false,
//   "subtotal": 1610,
//   "round_off": 0,
//   "discount_amount": 0,
//   "cgst_total": 0,
//   "sgst_total": 0,
//   "igst_total": 0,
//   "grand_total": 1610,
//   "total_profit": 163,
//   "amount_paid": 0,
//   "amount_due": 1610,
//   "payment_method": "credit",
//   "notes": "",
//   "bill_line_items": [
//     {
//       "item_name": "Oil Filter BS3/4/6",
//       "hsn_code": "84212300",
//       "unit": "Pcs",
//       "qty": 1,
//       "unit_price": 1300,
//       "discount_pct": 0,
//       "gst_rate": 0,
//       "cgst": 0,
//       "sgst": 0,
//       "igst": 0,
//       "line_total": 1300,
//       "sort_order": 0,
//       "total_buy_price": 1187,
//       "line_profit": 113,
//       "batch_allocations": [
//         {
//           "batch_id": "ba2e3583-88d7-477c-845d-84650cdacef5",
//           "qty": 1,
//           "buy_price": 1187,
//           "batch_number": "OPENING-STOCK"
//         }
//       ],
//       "write_off_recovery": 0,
//       "item_id": "f19a687d-327b-4f6b-b48d-3914c80638e4"
//     },
//     {
//       "item_name": "Bearing",
//       "hsn_code": "84828000",
//       "unit": "Pcs",
//       "qty": 1,
//       "unit_price": 310,
//       "discount_pct": 0,
//       "gst_rate": 0,
//       "cgst": 0,
//       "sgst": 0,
//       "igst": 0,
//       "line_total": 310,
//       "sort_order": 1,
//       "total_buy_price": 260,
//       "line_profit": 50,
//       "batch_allocations": [
//         {
//           "batch_id": "08de0737-cd7e-4de9-94b4-4cae6ecf1bca",
//           "qty": 1,
//           "buy_price": 260,
//           "batch_number": "OPENING-STOCK"
//         }
//       ],
//       "write_off_recovery": 0,
//       "item_id": "cbd54957-4d51-44c3-8c66-990a1811e8ea"
//     }
//   ]
// }
// 05.e_u_m_xija.js:71 [BILL-DBG preview hook] Object
// 0_dtx.~oahr~b.js:50 [DEBUG - API] 2. Safe Bill Data: {
//   "bill_number": "INV-2026/07/14-B2345",
//   "customer_type": "flying",
//   "customer_name": "Testing bill",
//   "customer_phone": "7894561541",
//   "customer_id": "5341150c-7aa5-49d3-9a77-05a15cace3f1",
//   "bill_date": "2026-07-14",
//   "due_date": "",
//   "vehicle_no": "",
//   "reference_name": "",
//   "terms_conditions": "",
//   "status": "issued",
//   "is_gst_bill": false,
//   "is_interstate": false,
//   "subtotal": 1610,
//   "round_off": 0,
//   "discount_amount": 0,
//   "cgst_total": 0,
//   "sgst_total": 0,
//   "igst_total": 0,
//   "grand_total": 1610,
//   "total_profit": 163,
//   "amount_paid": 0,
//   "amount_due": 1610,
//   "payment_method": "credit",
//   "notes": "",
//   "bill_line_items": [
//     {
//       "item_name": "Oil Filter BS3/4/6",
//       "hsn_code": "84212300",
//       "unit": "Pcs",
//       "qty": 1,
//       "unit_price": 1300,
//       "discount_pct": 0,
//       "gst_rate": 0,
//       "cgst": 0,
//       "sgst": 0,
//       "igst": 0,
//       "line_total": 1300,
//       "sort_order": 0,
//       "total_buy_price": 1187,
//       "line_profit": 113,
//       "batch_allocations": [
//         {
//           "batch_id": "ba2e3583-88d7-477c-845d-84650cdacef5",
//           "qty": 1,
//           "buy_price": 1187,
//           "batch_number": "OPENING-STOCK"
//         }
//       ],
//       "write_off_recovery": 0,
//       "item_id": "f19a687d-327b-4f6b-b48d-3914c80638e4"
//     },
//     {
//       "item_name": "Bearing",
//       "hsn_code": "84828000",
//       "unit": "Pcs",
//       "qty": 1,
//       "unit_price": 310,
//       "discount_pct": 0,
//       "gst_rate": 0,
//       "cgst": 0,
//       "sgst": 0,
//       "igst": 0,
//       "line_total": 310,
//       "sort_order": 1,
//       "total_buy_price": 260,
//       "line_profit": 50,
//       "batch_allocations": [
//         {
//           "batch_id": "08de0737-cd7e-4de9-94b4-4cae6ecf1bca",
//           "qty": 1,
//           "buy_price": 260,
//           "batch_number": "OPENING-STOCK"
//         }
//       ],
//       "write_off_recovery": 0,
//       "item_id": "cbd54957-4d51-44c3-8c66-990a1811e8ea"
//     }
//   ]
// }
// 0_dtx.~oahr~b.js:50 [DEBUG - API] 3. Final DB Insert Payload -> finalBillNumber: "INV-2026/07/14-B2345", finalBillDate: "2026-07-14" {
//   "bill_number": "INV-2026/07/14-B2345",
//   "customer_type": "flying",
//   "customer_name": "Testing bill",
//   "customer_phone": "7894561541",
//   "customer_id": "5341150c-7aa5-49d3-9a77-05a15cace3f1",
//   "bill_date": "2026-07-14",
//   "due_date": "",
//   "vehicle_no": "",
//   "reference_name": "",
//   "terms_conditions": "",
//   "status": "issued",
//   "is_gst_bill": false,
//   "is_interstate": false,
//   "subtotal": 1610,
//   "round_off": 0,
//   "discount_amount": 0,
//   "cgst_total": 0,
//   "sgst_total": 0,
//   "igst_total": 0,
//   "grand_total": 1610,
//   "total_profit": 163,
//   "amount_paid": 0,
//   "amount_due": 1610,
//   "payment_method": "credit",
//   "notes": "",
//   "bill_line_items": [
//     {
//       "item_name": "Oil Filter BS3/4/6",
//       "hsn_code": "84212300",
//       "unit": "Pcs",
//       "qty": 1,
//       "unit_price": 1300,
//       "discount_pct": 0,
//       "gst_rate": 0,
//       "cgst": 0,
//       "sgst": 0,
//       "igst": 0,
//       "line_total": 1300,
//       "sort_order": 0,
//       "total_buy_price": 1187,
//       "line_profit": 113,
//       "batch_allocations": [
//         {
//           "batch_id": "ba2e3583-88d7-477c-845d-84650cdacef5",
//           "qty": 1,
//           "buy_price": 1187,
//           "batch_number": "OPENING-STOCK"
//         }
//       ],
//       "write_off_recovery": 0,
//       "item_id": "f19a687d-327b-4f6b-b48d-3914c80638e4"
//     },
//     {
//       "item_name": "Bearing",
//       "hsn_code": "84828000",
//       "unit": "Pcs",
//       "qty": 1,
//       "unit_price": 310,
//       "discount_pct": 0,
//       "gst_rate": 0,
//       "cgst": 0,
//       "sgst": 0,
//       "igst": 0,
//       "line_total": 310,
//       "sort_order": 1,
//       "total_buy_price": 260,
//       "line_profit": 50,
//       "batch_allocations": [
//         {
//           "batch_id": "08de0737-cd7e-4de9-94b4-4cae6ecf1bca",
//           "qty": 1,
//           "buy_price": 260,
//           "batch_number": "OPENING-STOCK"
//         }
//       ],
//       "write_off_recovery": 0,
//       "item_id": "cbd54957-4d51-44c3-8c66-990a1811e8ea"
//     }
//   ]
// }
// 0_dtx.~oahr~b.js:43 [DEBUG - INVENTORY] Create Bill applied -1 to batch ba2e3583-88d7-477c-845d-84650cdacef5.
// 0_dtx.~oahr~b.js:43 [DEBUG - INVENTORY] Create Bill applied -1 to batch 08de0737-cd7e-4de9-94b4-4cae6ecf1bca.
// 0_dtx.~oahr~b.js:50 [DEBUG] Bill successfully created with ID: 77aca165-cb0d-47d3-b2ac-0e2809e0d6e7
// 0_dtx.~oahr~b.js:50 === [DEBUG - createBill END] ===

// 05.e_u_m_xija.js:71 [BILL-DBG preview hook] ObjectnextBillPreview: "INV-2026/09/29-1"tenantId: "b0c8e6d5-4528-468f-94e6-e0fd97dde8b1"[[Prototype]]: Object
// 0_dtx.~oahr~b.js:28 [DEBUG - API] Fetching Bill ID: 77aca165-cb0d-47d3-b2ac-0e2809e0d6e7 for Tenant: b0c8e6d5-4528-468f-94e6-e0fd97dde8b1
// 0_dtx.~oahr~b.js:43 [DEBUG - API] fetchBillById Supabase Result: Object
// 0j9kyohpeo1im.js:1 [DEBUG - BillForm] Setting bill_number to preview: undefined
// 0j9kyohpeo1im.js:1 [DEBUG - BillForm] RAW form data generated by React Hook Form: Objectbill_date: "2026-07-14"bill_number: "INV-2026/07/14-B2345"[[Prototype]]: Object
// 0j9kyohpeo1im.js:1 [DEBUG - BillForm] FINAL data being sent to parent onSubmit: Object
// 0_dtx.~oahr~b.js:51 
// === [DEBUG - updateBill] ===
// 0_dtx.~oahr~b.js:52 [DEBUG - API] 1. Initial Data received by API -> bill_number: "INV-2026/07/14-B2345", bill_date: "2026-07-14"
// 0_dtx.~oahr~b.js:52 [DEBUG - updateBill] Held Batches Map calculated: Object
// 0_dtx.~oahr~b.js:52 [DEBUG - updateBill] Active Batches Map sent to Engine: {
//   "f19a687d-327b-4f6b-b48d-3914c80638e4": [
//     {
//       "id": "ba2e3583-88d7-477c-845d-84650cdacef5",
//       "po_id": null,
//       "item_id": "f19a687d-327b-4f6b-b48d-3914c80638e4",
//       "buy_price": 1187,
//       "stock_qty": 3,
//       "tenant_id": "b0c8e6d5-4528-468f-94e6-e0fd97dde8b1",
//       "created_at": "2026-08-30T13:02:54.652654+00:00",
//       "sell_price": 1300,
//       "batch_number": "OPENING-STOCK"
//     }
//   ],
//   "cbd54957-4d51-44c3-8c66-990a1811e8ea": [
//     {
//       "id": "08de0737-cd7e-4de9-94b4-4cae6ecf1bca",
//       "po_id": null,
//       "item_id": "cbd54957-4d51-44c3-8c66-990a1811e8ea",
//       "buy_price": 260,
//       "stock_qty": 5,
//       "tenant_id": "b0c8e6d5-4528-468f-94e6-e0fd97dde8b1",
//       "created_at": "2026-08-30T12:47:32.107835+00:00",
//       "sell_price": 310,
//       "batch_number": "OPENING-STOCK"
//     }
//   ]
// }
// 0_dtx.~oahr~b.js:52 [DEBUG - API] 2. Data AFTER CalculationEngine -> bill_number: "INV-2026/07/14-B2345", bill_date: "2026-07-14"
// 0_dtx.~oahr~b.js:52 [DEBUG - API] 3. Final DB Update Payload -> finalBillNumber: "INV-2026/07/14-B2345", finalBillDate: "2026-07-14"
// 0_dtx.~oahr~b.js:43 [DEBUG - INVENTORY] Update Bill (Revert) applied 1 to batch ba2e3583-88d7-477c-845d-84650cdacef5.
// 0_dtx.~oahr~b.js:43 [DEBUG - INVENTORY] Update Bill (Revert) applied 1 to batch 08de0737-cd7e-4de9-94b4-4cae6ecf1bca.
// 0_dtx.~oahr~b.js:43 [DEBUG - INVENTORY] Update Bill (Apply) applied -1 to batch ba2e3583-88d7-477c-845d-84650cdacef5.
// 0_dtx.~oahr~b.js:43 [DEBUG - INVENTORY] Update Bill (Apply) applied -1 to batch 08de0737-cd7e-4de9-94b4-4cae6ecf1bca.
// 0_dtx.~oahr~b.js:52 [DEBUG] Bill successfully updated.
// 0_dtx.~oahr~b.js:52 === [DEBUG - updateBill END] ===

// 0_dtx.~oahr~b.js:28 [DEBUG - API] Fetching Bill ID: 77aca165-cb0d-47d3-b2ac-0e2809e0d6e7 for Tenant: b0c8e6d5-4528-468f-94e6-e0fd97dde8b1
// 0_dtx.~oahr~b.js:43 [DEBUG - API] fetchBillById Supabase Result: Object